name: Deploy RESTRO-APP to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
          npx update-browserslist-db@latest  # Fix browserslist warning

      - name: Disable CI for npm build on Windows CMD
        run: |
          set CI=false
          npm run build
        shell: cmd

      - name: Deploy build to IIS folder (CMD)
        shell: cmd
        run: |
          set destination=C:\inetpub\wwwroot\RestroApp
          if exist "%destination%" rmdir /s /q "%destination%"
          mkdir "%destination%"
          xcopy build "%destination%\" /s /e /y
          echo Deployment Complete!
